apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: 679625721250.dkr.ecr.eu-west-1.amazonaws.com/marketpulse-processor:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka:9092"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka:9092"
            # Add other environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 