apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketpulse-p2p-trading
  labels:
    app: marketpulse-p2p-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketpulse-p2p-trading
  template:
    metadata:
      labels:
        app: marketpulse-p2p-trading
    spec:
      containers:
      - name: p2p-trading
        image: marketpulse-p2p-trading:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres-service:5432/p2ptradingdb"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DATABASE_DRIVER
          value: "org.postgresql.Driver"
        - name: JPA_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: p2p-trading-service
spec:
  selector:
    app: marketpulse-p2p-trading
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP 